### ISSUE TITLE
Support working directory?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mainmatter/ember-asset-size-action#6]
My ember app isn't in the root of my repo:

https://github.com/NullVoxPopuli/emberclear/pull/279/checks?check_run_id=386020382

This is the config I used:
```yaml
name: Frontend Asset Sizes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: simplabs/ember-asset-size-action@v1
      working-directory: packages/frontend
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
working directory is supported by many other actions, afaik. 

Maybe that's just me not knowing how GH Actions syntax works. idk

I then tried this:
```yaml
name: Frontend Asset Sizes

on: [pull_request]

env:
  cwd: packages/frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0

    - uses: rwjblue/setup-volta@v1
      with:
        working-directory: ${{ env.cwd }}

    - uses: simplabs/ember-asset-size-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: ${{ env.cwd }}
```

which then gave the error: 
![image](https://user-images.githubusercontent.com/199018/72227224-f108a280-3567-11ea-8992-34aa8ccc4d00.png)
This looks like it's ignoring the working directory setting?
🤷‍♂
